{
 "title": "Execution Payloads Benchmarks Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus DS", "query": "prometheus" },
   { "name": "testid", "label": "Test ID", "query": { "query": "label_values(testid)" } },
   { "name": "quantile_stat", "label": "Trend Metrics Query", "query": { "query": "metrics(k6_http_req_duration_)" } },
   { "name": "adhoc_filter", "label": "AdhocFilter" }
  ]
 },
 "panels": [
  {
   "title": "Performance Summary",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "k6_http_req_duration_p90{tool=\"expb\", testid=~\"$testid\", name!=\"payload_fetch\", group!~\"::setup::.*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "k6_http_req_duration_p95{tool=\"expb\", testid=~\"$testid\", name!=\"payload_fetch\", group!~\"::setup::.*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "k6_http_req_duration_p99{tool=\"expb\", testid=~\"$testid\", name!=\"payload_fetch\", group!~\"::setup::.*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "k6_http_req_duration_med{tool=\"expb\", testid=~\"$testid\", name!=\"payload_fetch\", group!~\"::setup::.*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "k6_http_req_duration_max{tool=\"expb\", testid=~\"$testid\", name!=\"payload_fetch\", group!~\"::setup::.*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "k6_http_req_duration_min{tool=\"expb\", testid=~\"$testid\", name!=\"payload_fetch\", group!~\"::setup::.*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "k6_http_req_duration_avg{tool=\"expb\", testid=~\"$testid\", name!=\"payload_fetch\", group!~\"::setup::.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Performance Overview",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "avg by (testid) (k6_iteration_duration_$quantile_stat{tool=\"expb\", testid=~\"$testid\", name!=\"payload_fetch\", group!~\"::setup::.*\"})",
     "legendFormat": "http_req_duration_$quantile_stat - {{testid}}"
    },
    {
     "expr": "sum by (testid) (irate(k6_http_reqs_total{tool=\"expb\", testid=~\"$testid\", name!=\"payload_fetch\", group!~\"::setup::.*\"}[$__rate_interval]))",
     "legendFormat": "http_req_s  - {{testid}}"
    },
    {
     "expr": "sum by (testid) (irate(k6_http_reqs_total{tool=\"expb\", testid=~\"$testid\", expected_response=\"false\", name!=\"payload_fetch\", group!~\"::setup::.*\"}[$__rate_interval]))",
     "legendFormat": "http_req_s_errors  - {{testid}}"
    }
   ]
  },
  { "title": "Performance Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Iterations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(testid) (k6_iterations_total{tool=\"expb\", testid=~\"$testid\", name!=\"payload_fetch\", group!~\"::setup::.*\"})",
     "legendFormat": "{{testid}}"
    }
   ]
  },
  {
   "title": "Blocks per second",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "blocks/s" } },
   "targets": [
    {
     "expr": "sum by(testid) (irate(k6_iterations_total{tool=\"expb\", testid=~\"$testid\", name!=\"payload_fetch\", group!~\"::setup::.*\"}[$__rate_interval]))",
     "legendFormat": "{{testid}}"
    }
   ]
  },
  {
   "title": "HTTP request failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (testid) (k6_http_reqs_total{tool=\"expb\", testid=~\"$testid\", expected_response=\"false\", name!=\"payload_fetch\", group!~\"::setup::.*\"})",
     "legendFormat": "{{testid}}"
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "stat",
   "description": "Select a different Stat to change the query",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(testid) ({\"k6_http_req_duration_$quantile_stat\", tool=\"expb\", testid=~\"$testid\", jrpc_method=\"engine_newPayloadV3\", name!=\"payload_fetch\", group!~\"::setup::.*\"})",
     "legendFormat": "{{testid}}"
    }
   ]
  },
  {
   "title": "Transfer Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (testid) (irate(k6_data_sent_total{tool=\"expb\", testid=~\"$testid\", name!=\"payload_fetch\", group!~\"::setup::.*\"}[$__rate_interval]))",
     "legendFormat": "data_sent - {{testid}}"
    },
    {
     "expr": "avg by (testid) (irate(k6_data_received_total{tool=\"expb\", testid=~\"$testid\", name!=\"payload_fetch\", group!~\"::setup::.*\"}[$__rate_interval]))",
     "legendFormat": "data_received - {{testid}}"
    }
   ]
  },
  {
   "title": "Iterations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (testid) (k6_iteration_duration_$quantile_stat{tool=\"expb\", testid=~\"$testid\", name!=\"payload_fetch\", group!~\"::setup::.*\"})",
     "legendFormat": "iteration_duration_$quantile_stat - {{testid}}"
    },
    {
     "expr": "avg by (testid) (k6_dropped_iterations_total{tool=\"expb\", testid=~\"$testid\", name!=\"payload_fetch\", group!~\"::setup::.*\"})",
     "legendFormat": "dropped_iterations - {{testid}}"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "HTTP Latency Timings",
   "type": "timeseries",
   "description": "Select a different Stat to change the query\n\n<a href=\"https://k6.io/docs/using-k6/metrics/reference/#http\" target=\"_blank\">HTTP-specific built-in metrics</a>",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (testid, group) (k6_http_req_blocked_$quantile_stat{tool=\"expb\", testid=~\"$testid\", name!=\"payload_fetch\", group!~\"::setup::.*\"})",
     "legendFormat": "http_req_blocked_$quantile_stat - {{testid}}{{group}}"
    },
    {
     "expr": "avg by (testid, group) (k6_http_req_tls_handshaking_$quantile_stat{tool=\"expb\", testid=~\"$testid\", name!=\"payload_fetch\", group!~\"::setup::.*\"})",
     "legendFormat": "http_req_tls_handshaking_$quantile_stat - {{testid}}{{group}}"
    },
    {
     "expr": "avg by (testid, group) (k6_http_req_sending_$quantile_stat{tool=\"expb\", testid=~\"$testid\", name!=\"payload_fetch\", group!~\"::setup::.*\"})",
     "legendFormat": "http_req_sending_$quantile_stat - {{testid}}{{group}}"
    },
    {
     "expr": "avg by (testid, group) (k6_http_req_waiting_$quantile_stat{tool=\"expb\", testid=~\"$testid\", name!=\"payload_fetch\", group!~\"::setup::.*\"})",
     "legendFormat": "http_req_waiting_$quantile_stat - {{testid}}{{group}}"
    },
    {
     "expr": "avg by (testid, group) (k6_http_req_receiving_$quantile_stat{tool=\"expb\", testid=~\"$testid\", name!=\"payload_fetch\", group!~\"::setup::.*\"})",
     "legendFormat": "http_req_receiving_$quantile_stat - {{testid}}{{group}}"
    }
   ]
  },
  {
   "title": "HTTP Latency Stats",
   "type": "timeseries",
   "description": "Select a different Stat to change the query",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (testid, group) (k6_http_req_duration_$quantile_stat{tool=\"expb\", testid=~\"$testid\", name!=\"payload_fetch\", group!~\"::setup::.*\"})",
     "legendFormat": "http_req_duration_$quantile_stat - {{testid}}{{group}}"
    },
    {
     "expr": "avg by (testid, group) (k6_http_req_duration_$quantile_stat{tool=\"expb\", testid=~\"$testid\", expected_response=\"true\", name!=\"payload_fetch\", group!~\"::setup::.*\"})",
     "legendFormat": "success_http_req_duration_$quantile_stat - {{testid}}{{group}}"
    },
    {
     "expr": "avg by (testid, group) (k6_http_req_duration_$quantile_stat{tool=\"expb\", testid=~\"$testid\", expected_response=\"false\", name!=\"payload_fetch\", group!~\"::setup::.*\"})",
     "legendFormat": "errors_http_req_duration_$quantile_stat - {{testid}}{{group}}"
    }
   ]
  },
  {
   "title": "Gas Usage per Payload (Processing)",
   "type": "xychart",
   "description": "Gas Usage calculation for engine_newPayload request waiting time.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "k6_expb_slowest_processing{tool=\"expb\", testid=~\"$testid\", name!=\"payload_fetch\", group!~\"::setup::.*\"}",
     "legendFormat": "{{testid}}"
    }
   ]
  },
  {
   "title": "Gas Usage per Payload (Full)",
   "type": "xychart",
   "description": "Gas Usage calculation for full engine_newPayload request duration.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "k6_expb_slowest_payloads{tool=\"expb\", testid=~\"$testid\", name!=\"payload_fetch\", group!~\"::setup::.*\"}",
     "legendFormat": "{{testid}}"
    }
   ]
  },
  {
   "title": "Payloads Durations",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "k6_expb_slowest_payloads{tool=\"expb\", testid=~\"$testid\", name!=\"payload_fetch\", group!~\"::setup::.*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "k6_expb_slowest_processing{tool=\"expb\", testid=~\"$testid\", name!=\"payload_fetch\", group!~\"::setup::.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (testid) (irate(k6_http_reqs_total{tool=\"expb\", testid=~\"$testid\", name!=\"payload_fetch\", group!~\"::setup::.*\"}[$__rate_interval]))",
     "legendFormat": "http_req_s - {{testid}}"
    },
    {
     "expr": "sum by (testid) (irate(k6_http_reqs_total{tool=\"expb\", testid=~\"$testid\", expected_response=\"false\", name!=\"payload_fetch\", group!~\"::setup::.*\"}[$__rate_interval]))",
     "legendFormat": "http_req_s_errors - {{testid}}"
    },
    {
     "expr": "sum by (testid) (irate(k6_http_reqs_total{tool=\"expb\", testid=~\"$testid\", expected_response=\"true\", name!=\"payload_fetch\", group!~\"::setup::.*\"}[$__rate_interval]))",
     "legendFormat": "http_req_s_success - {{testid}}"
    }
   ]
  },
  {
   "title": "Blocks Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(testid) (irate(k6_iteration_total{tool=\"expb\", testid=~\"$testid\", expected_response=\"true\", name!=\"payload_fetch\", group!~\"::setup::.*\"}[$__rate_interval]))",
     "legendFormat": "http_req_s_success - {{testid}}"
    }
   ]
  },
  {
   "title": "Requests by URL",
   "type": "table",
   "description": "min/max/p95/p99 depends on the available Quantile Stats",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 112 },
   "targets": [
    {
     "expr": "k6_http_req_duration_min{tool=\"expb\", testid=~\"$testid\", name!=\"payload_fetch\", group!~\"::setup::.*\"}",
     "legendFormat": "min"
    },
    {
     "expr": "k6_http_req_duration_max{tool=\"expb\", testid=~\"$testid\", name!=\"payload_fetch\", group!~\"::setup::.*\"}",
     "legendFormat": "max"
    },
    {
     "expr": "k6_http_req_duration_p95{tool=\"expb\", testid=~\"$testid\", name!=\"payload_fetch\", group!~\"::setup::.*\"}",
     "legendFormat": "p95"
    },
    {
     "expr": "k6_http_req_duration_p99{tool=\"expb\", testid=~\"$testid\", name!=\"payload_fetch\", group!~\"::setup::.*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "k6_http_req_duration_avg{tool=\"expb\",testid=~\"$testid\", name!=\"payload_fetch\", group!~\"::setup::.*\"}",
     "legendFormat": "avg"
    },
    {
     "expr": "k6_http_req_duration_med{tool=\"expb\",testid=~\"$testid\", name!=\"payload_fetch\", group!~\"::setup::.*\"}",
     "legendFormat": "med"
    }
   ]
  },
  { "title": "Checks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 124 } },
  {
   "title": "Checks list",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
   "targets": [
    {
     "expr": "round(k6_checks_rate{tool=\"expb\", testid=~\"$testid\", name!=\"payload_fetch\", group!~\"::setup::.*\"}, 0.1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checks Success Rate (aggregate individual checks)",
   "type": "timeseries",
   "description": "Filter by check name to query a particular check",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "avg by (testid) (round(k6_checks_rate{tool=\"expb\", testid=~\"$testid\", name!=\"payload_fetch\", group!~\"::setup::.*\"}, 0.1)*100)",
     "legendFormat": "k6_checks_rate - {{testid}}"
    }
   ]
  }
 ]
}